### ISSUE TITLE
World map of electronic passports

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/proof-of-passport#106]
Create a world map visualization of countries' signature algorithms we can host at map.proofofpassport.com.

Hovering over a country should display:
- if it issues electronic passports
- the signature algorithms it uses to sign passports, and ~ how many passports have been signed with each
- if they are currently supported by proof of passport

At first, it can be based on [this json](https://github.com/zk-passport/proof-of-passport/blob/main/registry/outputs/signature_algorithms.json), which shows the number of intermediate certificates (DSCs) issued by each country and their signature algorithm. We can assume for now each DSC is used to sign in the order of 100k passports. This json has been created by parsing the ICAO registry but we should extend it to other registries. It should be easy to add new data.

Other relevant docs on e-passports [here](https://hackmd.io/@TCEn_IDhTDWLjwyItiiBcQ/BJ4LX0m9p), and [here](https://www.readid.com/hubfs/Documents/Whitepapers%20and%20Reports/ReadID%20Whitepaper%20%7C%20ReadID%20documents%20summary.pdf).

**Comment by Gerson2102** [comment]
Hey can i work on this one?

**Comment by Gerson2102** [comment]
I don't know if I'm wrong or something. But the tech stack of the project changed? I remember to see a lot of kotlin and a little bit of Rust.

**Comment by 0xturboblitz** [comment]
Hi
You would do this in typescript, this is purely UI, not part of the mobile app.

**Comment by Vignesh-PS** [comment]
hi @0xturboblitz, can i work on this as a part of ODHack? 
i would use following reference for map visualization,
https://www.react-simple-maps.io/

**Comment by remicolin** [comment]
hey @Vignesh-PS 
Yes you can work on this for the ODHack, please inform us if you start working on this so we can suspend the issue for a time.

**Comment by remicolin** [comment]
Hi @Vignesh-PS 
Do you have any updates to share with us?

**Comment by Vignesh-PS** [comment]
hi @remicolin , few changes made for visualization as a map with tooltip info with dummy data. formatting signature_algorithms.json data to given as input to a map now.

**Comment by remicolin** [comment]
Do you have some code/demo to share with us?

**Comment by Vignesh-PS** [comment]
sure, added preview screenshot here
https://github.com/Vignesh-PS/proof-of-passport/tree/map-passport/map-passport

**Comment by Vignesh-PS** [comment]
https://github.com/zk-passport/pop-landing-page/pull/1

**Comment by 0xturboblitz** [comment]
Closing, done here: https://github.com/zk-passport/pop-landing-page/pull/1
