### ISSUE TITLE
Implement MGF1 in circom

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/proof-of-passport#109]
Implement MGF1 in circom, which will be a key part of the verification of RSA-PSS in circom, c.f. https://github.com/zk-passport/proof-of-passport/issues/38.

I would take inspiration from [this](https://github.com/shigeki/ohtsu_rsa_pss_js/blob/41f98614e9080080103db6b23e79cf6d8b78f794/rsa_pss.js#L114).

**Comment by Prabhat1308** [comment]
Hi. I have some experience in Circom and would like to take up this issue !

**Comment by 0xturboblitz** [comment]
Cool please explain how you would tackle it

**Comment by seshanthS** [comment]
Hey @0xturboblitz, I would like to work on this issue. 

I am a Solidity Dev, with some Circom experience. I have used it in few hobby projects before.

I found this spec (https://datatracker.ietf.org/doc/html/rfc8017#appendix-B.2.1) and will use it to tackle this issue

**Comment by remicolin** [comment]
Nice @Prabhat1308 @seshanthS,
Can you take a look at the circuits repo and give a detailed plan on how you will tackle the issue ?
If you want to work on circom circuits there is also other signatures algorithm to implement.

**Comment by 0xturboblitz** [comment]
Closing, done in https://github.com/zk-passport/proof-of-passport/pull/115
