### ISSUE TITLE
Add compliance with W3C's VC standard

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/proof-of-passport#125]
The most accepted standard for verifiable credentials is the [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/) established by the [World Wide Web Consortium](https://www.w3.org/).

Proof of Passport should be able to comply with that standard.

The way it could work is by formatting the current attestation data according to the standard, then either:
- Create a Proof of Passport App letting users export their proof as a VC
- Add the VC format by default for new apps that need to verify proofs offchain with the sdk

**Comment by CristopherAguilar10** [comment]
Hello @0xturboblitz , I would like to create my first issue and this one seems quite interesting. Can I help with it?

**Comment by 0xturboblitz** [comment]
Hi, yes and feel free to [dm](https://t.me/FlorentTavernier) for any questions

**Comment by CristopherAguilar10** [comment]
@0xturboblitz Ok, thank you very much. We will be in touch

**Comment by 0xturboblitz** [comment]
Some preliminary work on https://github.com/zk-passport/proof-of-passport/pull/160.

Closing because not a priority right now, as we're not sure which standard will be needed, and have not received requests to use a specific one for not.
