### ISSUE TITLE
Adapt RSA to 3072 and 4096 bit keys

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/proof-of-passport#132]
The implementation of [RSA in circom](https://github.com/zkemail/zk-email-verify/blob/main/packages/circuits/lib/rsa.circom) we use supports 2048 bit keys.

One of the things we will need to [validate certificate chains](https://github.com/zk-passport/proof-of-passport/issues/37) is adapting it to support 3072 and 4096 bit keys, as keys of those sizes are used by CSCAs to sign DSCs.

**Comment by remicolin** [comment]
I already [implemented](https://github.com/zk-passport/proof-of-passport/blob/csca/circuits/test/dsc_4096.test.ts) certificated chain verification with 2048 bits rsa dsc and 4096 bits csca key on [csca branch](https://github.com/zk-passport/proof-of-passport/tree/csca), working well.
proving time is slow but i think **n** and **k** parameters can be optimized.
