### ISSUE TITLE
Refactor /common

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/proof-of-passport#54]
Currently, the `/common` directory contains utils and inputs used in multiple subdirs. There are sometimes compatibility issues because the code is sometimes run in ts-node scripts from `/contracts` and `/circuits` and sometimes from the react native environment of the app.

It would be cleaner to factor this out and in the long run have an sdk with packages.

**Comment by sasasamaes** [comment]
I would love to work on this project, I would like to work on this issue, where can I have more communication for questions in telegram?

**Comment by 0xturboblitz** [comment]
hi
yes, you can dm me at @FlorentTavernier on telegram

**Comment by 0xturboblitz** [comment]
Not sure this is a priority or even something we want rn
