### ISSUE TITLE
Add support for DG11: optional attributes

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/proof-of-passport#65]
Some countries including France fill the DG11 data group. See docs [here](https://www.icao.int/publications/documents/9303_p10_cons_en.pdf#page=70).

It contains optional information like:
- Place of birth
- Permanent address
- Telephone
- Profession

It would be great to support disclosure of those attributes in the circuit. This would include:
- In including DG11 when it's present in the commitment during registration
- Revealing selectively some bytes of it during disclosure, like it's done with DG1

**Comment by danielcdz** [comment]
Hello @0xturboblitz I'm Daniel from Costa Rica! I have over 3 years of experience as a software engineer, I'm making my first contributions to OSS in web3 and blockchain projects, and I would like to help solve this issue! This is my 2nd ODHack!

**Comment by 0xturboblitz** [comment]
Nice! dm me if you have any questions

**Comment by danielcdz** [comment]
@0xturboblitz sure! I think you forgot to assign me the issue btw

**Comment by 0xturboblitz** [comment]
Hi, can you describe how you would tackle it before I assign it to you?

**Comment by mdabir1203** [comment]
I am a complete beginner and I am curious where to start for ODHack issues > ?

**Comment by od-hunter** [comment]
Can I be assigned this issue? I’ll update the circuits to include the attributes as instructed both during registration/disclosure. I’ll send a draft pr within 24 hours. Thank you

**Comment by od-hunter** [comment]
Thank you  sir🙏🏾

**Comment by od-hunter** [comment]
Good day sir @0xturboblitz ,  sorry I’m just getting back to you. I started solving this but I got sick and had to stop(seriously sick). I’m still sick as I type this, please kindly reassign this issue to someone else.🙏🏾 I’ll take up another task in the next OD hack if I feel better by then. I apologize once more please. Thank you for understanding.

**Comment by 0xturboblitz** [comment]
Closing it right now as:
- It's quite low priority, we don't see good use cases now
- Only some countries put this data
- Adding DG11 to the commitment only when it's included would increase the complexity of the registration and disclosure circuits significantly
