### ISSUE TITLE
How do you achieve selective disclosure, and is it need to generate zkproof for verification？

### ISSUE THREAD

**Issue by youwenbusi** [zk-passport/proof-of-passport#70]

**Comment by 0xturboblitz** [comment]
Hi

Prefer DMing me for this kind of questions.

Selective disclosure is achieved with the `reveal_bitmap` [here](https://github.com/zk-passport/proof-of-passport/blob/main/circuits/test/passport.test.ts#L37) that selects the bytes to reveal in the MRZ.
You can choose to hide it completely by passing a bitmap full of zeros.
