### ISSUE TITLE
Gitcoin Passport stamp support

### ISSUE THREAD

**Issue by numtel** [zk-passport/proof-of-passport#94]
Hello,

I just saw this project on Gitcoin and I just want to say very cool. I've been waiting to see this since Ian Miers' presentation at Devcon in Bogota. I've got to get a phone with an NFC reader :smiley: 

Two years ago, I made [Coinpassport](coinpassport.net), using Stripe Identity to verify passports on chain. Stripe's API doesn't sign the response though and zkTLS wasn't around back then (or on my radar) so I had to sign the results on my own server. Nobody wants this kind of centralized service though. My full support goes out to you. If you want anything from my project (even the domain) it's yours... :clap:

A year ago I made a PR for a Coinpassport stamp on Gitcoin Passport but never got any response. Maybe it can be used as a template

https://github.com/gitcoinco/passport/pull/1063

Anyways best of luck! And I can't wait to see dApps built with this quick and easy Sybil resistance method.

Ben

**Comment by 0xturboblitz** [comment]
Thanks! Taking a look. Happy you like it.
